<a href="https://colab.research.google.com/github/karanveer-sharma/pythontraining_with_ai/blob/main/loogisticreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os
import kagglehub
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
path = kagglehub.dataset_download("blastchar/telco-customer-churn")
telco=pd.read_csv(os.path.join(path,"WA_Fn-UseC_-Telco-Customer-Churn.csv"))
telco.head()

Using Colab cache for faster access to the 'telco-customer-churn' dataset.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
telco.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
telco.shape

(7043, 21)

In [ ]:
telco.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
telco["TotalCharges"]=pd.to_numeric(telco["TotalCharges"], errors="coerce").fillna(0)
telco.drop("customerID",axis=1,inplace=True)
telco[["TotalCharges"]]

      TotalCharges
0            29.85
1          1889.50
2           108.15
3          1840.75
4           151.65
...            ...
7038       1990.50
7039       7362.90
7040        346.45
7041        306.60
7042       6844.50

[7043 rows x 1 columns]

In [ ]:
telco["Churn"]=telco["Churn"].replace({"Yes": 1, "No":0})
telco["Churn"].head()

/tmp/ipython-input-1103275960.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  telco["Churn"]=telco["Churn"].replace({"Yes": 1, "No":0})

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [ ]:
categorial_cols=["gender","Partner","Dependents","PhoneService","Contract","PaperlessBilling"]
telco_ecoded=pd.get_dummies(telco,columns=categorial_cols,drop_first=True)
telco_ecoded.head()

,SeniorCitizen,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,...,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes
0,0,1,No phone service,DSL,No,Yes,No,No,No,No,...,29.85,29.85,0,False,True,False,False,False,False,True
1,0,34,No,DSL,Yes,No,Yes,No,No,No,...,56.95,1889.50,0,True,False,False,True,True,False,False
2,0,2,No,DSL,Yes,Yes,No,No,No,No,...,53.85,108.15,1,True,False,False,True,False,False,True
3,0,45,No phone service,DSL,Yes,No,Yes,Yes,No,No,...,42.30,1840.75,0,True,False,False,False,True,False,False
4,0,2,No,Fiber optic,No,No,No,No,No,No,...,70.70,151.65,1,False,False,False,True,False,False,True

In [ ]:
X=telco_ecoded[["SeniorCitizen","tenure","MonthlyCharges","TotalCharges","gender_Male","Partner_Yes","Dependents_Yes","PhoneService_Yes","Contract_One year","Contract_Two year","PaperlessBilling_Yes"]]
y=telco_ecoded["Churn"]
X.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes'],
      dtype='object')

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
model= LogisticRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)
y_pred=model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print("Model Accuracy:",model.score(X_test,y_test))
print("\n classification Report :\n", classification_report(y_test,y_pred))

Model Accuracy: 0.8048261178140526

 classification Report :
               precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.66      0.54      0.59       373

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.73      1409
weighted avg       0.80      0.80      0.80      1409