<a href="https://colab.research.google.com/github/karanveer-sharma/pythontraining_with_ai/blob/main/titanicdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
try:
  Titanic_data=pd.read_csv("Titanic-Dataset.csv")
  print("suceesfully upload")

except:
  print("Error")

suceesfully upload

In [ ]:
df_titanic = pd.DataFrame(Titanic_data)
display(df_titanic.head())
display(df_titanic.info())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

None

In [ ]:
display(df_titanic.describe(include="all"))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [ ]:
#missing age number
null_age = df_titanic["Age"].isnull().sum
print(f"missing values in age : {null_age()}")

missing values in age : 177

In [ ]:
#total passengers survived
survive=df_titanic["Survived"].sum()
print(f"the number of survived : {survive}")

the number of survived : 342

In [ ]:
# filling null values
df_titanic["Age"]=df_titanic["Age"].fillna(df_titanic["Age"].mean())
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [ ]:
df_titanic=df_titanic.drop("Cabin", axis = 1)
display(df_titanic.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [ ]:
#percentage of female survivers compared to males
female_survive_total = df_titanic[df_titanic['Sex'] == 'female']['Survived'].sum()
female_percentatge = (female_survive_total / len(df_titanic[df_titanic['Sex'] == 'female'])) * 100
print(f"The total number of female survivors is = {female_percentatge:.2f}")

male_survive_total = df_titanic[df_titanic['Sex'] == 'male']['Survived'].sum()
male_percentatge = (male_survive_total / len(df_titanic[df_titanic['Sex'] == 'male'])) * 100
print(f"The total number of male survivors is = {male_percentatge}")

total_survivers = female_survive_total + male_survive_total
total_percentage = female_survive_total/ total_survivers *100
print(f"The female survivors in comparison to male survivors is = {total_percentage:.2f}%")

The total number of female survivors is = 74.20
The total number of male survivors is = 18.890814558058924
The female survivors in comparison to male survivors is = 68.13%

In [ ]:
#highest survivor class
class_survivors = df_titanic[df_titanic['Survived'] == 1]['Pclass'].value_counts()
highest_survivor_class = class_survivors.idxmax()
print(f"The class that has highest survivores = {highest_survivor_class} Class")

The class that has highest survivores = 1 Class

In [ ]:
#number of passanger which were alone
df_titanic["FamilySize"]= df_titanic["SibSp"]+df_titanic["Parch"]
alone = df_titanic[df_titanic["FamilySize"] ==0].shape[0]
print(f"the number of travelers which were alone is = {alone}")

the number of travelers which were alone is = 537

In [ ]:
#Average fare paid by class 1
Average_fare = df_titanic[df_titanic["Pclass"]==1]["Fare"].mean()
print(f"Average fair paid by class 1 : {Average_fare}")

Average fair paid by class 1 : 84.1546875

In [ ]:
#number of people under 18
children= df_titanic[df_titanic["Age"]<18].shape[0]
print(f"the number of passanger under 18 ={children}")

the number of passanger under 18 =113

In [ ]:
#port embarked most passanger board the ship
port = df_titanic["Embarked"].value_counts().idxmax()
print(f"the port had most passangers : {port} port")

the port had most passangers : S port

In [ ]:
#most common tittle
df_titanic["Title"] = df_titanic["Name"].str.extract(r",\s*([^\.]+)\.")
most_common_title = df_titanic['Title'].value_counts().idxmax()
print(f"the most common title = {most_common_title}")

the most common title = Mr

In [ ]:
couples = df_titanic[(df_titanic['FamilySize'] == 1) & (df_titanic['Survived'] == 1)].shape[0]
print(f"The number of couples that survived is = {couples}")

The number of couples that survived is = 89

In [ ]:
summary = {
    "questions" : [
        "Missing values in Age column",
        "Total survivors",
        "Percentage of female survivors",
        "Percentage of male survivors",
        "Female survivors in comparison to male survivors",
        "Class with highest survivors",
        "Passengers traveling alone",
        "Average fare in Pclass 1",
        "Children under 18",
        "Port with most passengers boarded",
        "Most common title",
        "Couples survived"
    ],
    "awnsers" : [
        null_age,
        survive,
        female_percentatge,
        male_percentatge,
        total_percentage,
        highest_survivor_class,
        alone,
        Average_fare,
        children,
        port,
        most_common_title,
        couples
    ]
}
summary_Data = pd.DataFrame(summary)
display(summary_Data)

,questions,awnsers
0,Missing values in Age column,<bound method Series.sum of 0 False\n1 ...
1,Total survivors,342
2,Percentage of female survivors,74.203822
3,Percentage of male survivors,18.890815
4,Female survivors in comparison to male survivors,68.128655
5,Class with highest survivors,1
6,Passengers traveling alone,537
7,Average fare in Pclass 1,84.154687
8,Children under 18,113
9,Port with most passengers boarded,S
10,Most common title,Mr
11,Couples survived,89